### ISSUE TITLE
ec_grasps_example1 - key error [up_speed]

### ISSUE THREAD

**Issue by psotiropoulos** [SoMa-Project/ec_grasp_planner#2]
@cerdogan running the example 1 as described (v1.2) returns with an error: _KeyError: 'up_speed'_. 
`rosrun ec_grasp_planner planner.py --rviz --robot_base_frame camera_rgb_optical_frame --grasp WallGrasp`
The default handarm argument is RBOHand2WAM and up_speed is not defined for the wall grasp there. 

While running it passing `--handarm RBOHand2Kuka` all seems connected but I get, what appears to be, a wrong plan (see attached photo).

![rviz_screenshot_ec_grasps_example1](https://cloud.githubusercontent.com/assets/12898010/25338129/15665496-28f6-11e7-8a44-ae2c55c20e60.png)

**Comment by cerdogan** [comment]
Hello Panos,

Please follow the instructions only in Section 5.iii (Kuka Arm in Gazebo Simulation with TRIK Controller). In fact, the videos I sent earlier might even be a better demonstration of the commands you want to run.

Regarding this example, this was Section 5.i, correct? I am not sure what the problem is exactly but I think we should first take a look at 5.iii.

**Comment by psotiropoulos** [comment]
Hi Can,

yes this is 5.1 Planning based on PCD Input. I normally go through all of
them.
I'll test 5.3 and if there is any problem there I'll open a separate issue.

Panos
