### ISSUE TITLE
Grasp success estimator behaving weirdly

### ISSUE THREAD

**Issue by ptriantd-ocado** [SoMa-Project/ec_grasp_planner#54]
We have the following issue with the grasp success estimator:

We have calculated the mean and std with the calculate_success_estimator_object_params script using the difference model. Our standard deviations are very very small (in the order of 0.006) which we thought is to be expected because we are using objects with standard weights.

Then we put these values in the object_param.yaml. 

So, we grasp a mango which has a weight of 0.4 kg and the difference in our measurements is 0.33 kg. Then, in the GUI all the grasp_estimator states have 0% probability, but the grasp estimator is sending a NO_OBJECT_GRASPED msg and the hand releases the object...

Any idea what might be going wrong? @JannisW

**Comment by ptriantd-ocado** [comment]
I think I had miscalculated the noise of our F/T sensor. It seems to work now, so I will close and reopen if the problem reappears

**Comment by JannisW** [comment]
The grasp success estimator should never return 0% probability for all classes. Even with wrong F/T noise calculation. Might be just a visualization bug in the GUI (or a numerical issue as the result of very small probabilities due to the wrong F/T noise).
Do you have a rosbag of a run in which that issue appears? 
Let me know as soon as that problem reappears. In that case it would be helpful to also record the topic `/graspSuccessEstimator/confidence_all`
